# This workflow will install Python dependencies, run tests and lint
# with a single version of Python For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: FIAT CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with flake8
        run: |
          python -m pip install flake8
          python -m flake8 --statistics .
      - name: Check documentation style
        run: |
          python -m pip install pydocstyle
          python -m pydocstyle .
      - name: Install FIAT and CI dependencies
        run: |
          python -m pip install '.[test]'
          python -m pip install coveralls pytest-cov
      - name: Test FIAT
        run: DATA_REPO_GIT="" python -m pytest --cov=FIAT/ test/FIAT
      - name: Test FInAT
        run: DATA_REPO_GIT="" python -m pytest --cov=finat/ --cov=gem/ test/finat
      - name: Coveralls
        if: ${{ github.repository == 'FEniCS/fiat' && github.head_ref == '' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: coveralls
